name: engine_pdf
description: Stub PDF reader engine
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  kernel:
    path: ../kernel
  foundation_domain:
    path: ../../foundation/domain



