name: full_reader

packages:
  - apps/mobile
  - apps/desktop
  - packages/foundation/core
  - packages/foundation/domain
  - packages/foundation/application
  - packages/infrastructure/data
  - packages/engines/engine_api
  - packages/engines/epub
  - packages/engines/pdf
  - packages/engines/audio
  - packages/engines/ldf

scripts:
  bootstrap: melos bootstrap
  pubget: melos exec -- flutter pub get
  format: melos exec -- dart format lib test