name: foundation_application
description: Application services/usecases for reader
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  foundation_domain:
    path: ../domain


